const escapeHtml = (value) =>
  String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');

const valueOrFallback = (value, fallback = '') => {
  const text = String(value ?? '').trim();
  return text || fallback;
};

const formatDisplayDate = (value) => {
  if (!value) return '';
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return String(value);

  return parsed.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
};

const formatDoctorName = (value) => {
  const name = valueOrFallback(value);
  if (!name) return 'your doctor';
  if (/^dr\.?\s/i.test(name)) return name;
  return `Dr. ${name}`;
};

const buildPrescriptionEmailSubject = ({ doctorName, prescriptionNumber } = {}) => {
  const doctorPart = valueOrFallback(doctorName) ? ` from ${formatDoctorName(doctorName)}` : '';
  const numberPart = valueOrFallback(prescriptionNumber) ? ` (${prescriptionNumber})` : '';
  return `Your Medi Meet Prescription${doctorPart}${numberPart}`;
};

const buildPrescriptionEmailHtml = ({
  patientName,
  doctorName,
  specialization,
  appointmentDate,
  prescriptionNumber,
  supportEmail,
  messageType = 'uploaded',
} = {}) => {
  const safePatientName = escapeHtml(valueOrFallback(patientName, 'Patient'));
  const safeDoctorName = escapeHtml(formatDoctorName(doctorName));
  const safeSpecialization = escapeHtml(valueOrFallback(specialization));
  const safeDate = escapeHtml(formatDisplayDate(appointmentDate));
  const safePrescriptionNumber = escapeHtml(valueOrFallback(prescriptionNumber));
  const safeSupportEmail = escapeHtml(valueOrFallback(supportEmail, 'medimeet.support@gmail.com'));
  const actionText = messageType === 'generated'
    ? 'Your prescription has been generated by your doctor and is attached to this email.'
    : 'Your doctor has uploaded your prescription and it is attached to this email.';
  const detailsRows = [
    safePrescriptionNumber ? ['Prescription No.', safePrescriptionNumber] : null,
    ['Doctor', safeDoctorName],
    safeSpecialization ? ['Specialization', safeSpecialization] : null,
    safeDate ? ['Consultation Date', safeDate] : null,
  ].filter(Boolean).map(([label, value]) => `
    <tr>
      <td style="padding:9px 0;border-bottom:1px solid #e8eef3;color:#66758a;font-size:13px;line-height:1.4;">${label}</td>
      <td align="right" style="padding:9px 0;border-bottom:1px solid #e8eef3;color:#172033;font-size:13px;line-height:1.4;font-weight:700;">${value}</td>
    </tr>
  `).join('');

  return `
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Your Medi Meet Prescription</title>
      </head>
      <body style="margin:0;padding:0;background:#eef6f8;font-family:Arial,Helvetica,sans-serif;color:#172033;">
        <div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">
          Your Medi Meet prescription PDF is attached to this email.
        </div>
        <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#eef6f8;padding:32px 12px;">
          <tr>
            <td align="center">
              <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px;background:#ffffff;border-radius:18px;overflow:hidden;border:1px solid #d7e8eb;box-shadow:0 18px 50px rgba(11,110,125,0.12);">
                <tr>
                  <td style="background:#0b6e7d;padding:0;color:#ffffff;">
                    <table role="presentation" width="100%" cellspacing="0" cellpadding="0">
                      <tr>
                        <td style="padding:30px;">
                          <table role="presentation" width="100%" cellspacing="0" cellpadding="0">
                            <tr>
                              <td width="78" valign="top" style="width:78px;">
                                <div style="width:68px;height:68px;border-radius:18px;background:#ffffff;color:#0b6e7d;text-align:center;line-height:68px;font-size:21px;font-weight:800;letter-spacing:0.02em;">MM</div>
                              </td>
                              <td valign="top">
                                <div style="font-size:13px;letter-spacing:0.16em;text-transform:uppercase;opacity:0.9;">Medi Meet Care Team</div>
                                <h1 style="margin:8px 0 0;font-size:27px;line-height:1.25;font-weight:800;">Your prescription is ready</h1>
                                <p style="margin:10px 0 0;font-size:14px;line-height:1.6;opacity:0.94;">The prescription PDF from your consultation is attached for your records.</p>
                              </td>
                            </tr>
                          </table>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td style="padding:32px 30px 28px;">
                    <p style="margin:0 0 16px;font-size:16px;line-height:1.65;color:#172033;">Dear <strong>${safePatientName}</strong>,</p>
                    <p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#35445a;">
                      ${escapeHtml(actionText)} Please review the document carefully and follow the dosage, timing, and care instructions shared by <strong>${safeDoctorName}</strong>${safeSpecialization ? ` (${safeSpecialization})` : ''}.
                    </p>

                    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f4faf9;border:1px solid #cde7e5;border-radius:14px;margin:0 0 22px;">
                      <tr>
                        <td style="padding:18px 20px;">
                          <table role="presentation" width="100%" cellspacing="0" cellpadding="0">
                            <tr>
                              <td width="58" valign="middle" style="width:58px;">
                                <div style="width:46px;height:46px;border-radius:12px;background:#0b6e7d;color:#ffffff;text-align:center;line-height:46px;font-size:13px;font-weight:800;letter-spacing:0.05em;">PDF</div>
                              </td>
                              <td valign="middle">
                                <div style="font-size:15px;line-height:1.4;color:#172033;font-weight:800;">Prescription attached</div>
                                <div style="font-size:13px;line-height:1.55;color:#536175;">Keep this document for your medical records and follow-up visits.</div>
                              </td>
                            </tr>
                          </table>
                        </td>
                      </tr>
                    </table>

                    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#ffffff;border:1px solid #d7e8eb;border-radius:14px;margin:0 0 22px;">
                      <tr>
                        <td style="padding:18px 20px;">
                          <div style="font-size:12px;letter-spacing:0.08em;text-transform:uppercase;color:#0b6e7d;font-weight:800;margin-bottom:8px;">Prescription details</div>
                          <table role="presentation" width="100%" cellspacing="0" cellpadding="0">
                            ${detailsRows}
                          </table>
                        </td>
                      </tr>
                    </table>

                    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#fff8ed;border:1px solid #f0dfc5;border-radius:14px;margin:0 0 22px;">
                      <tr>
                        <td style="padding:15px 18px;">
                          <p style="margin:0;font-size:14px;line-height:1.65;color:#5c4630;">
                            If anything in the prescription is unclear, contact your doctor before changing or stopping any medicine.
                          </p>
                        </td>
                      </tr>
                    </table>

                    <p style="margin:0 0 16px;font-size:14px;line-height:1.7;color:#536175;">
                      If your symptoms worsen, you notice any severe reaction, or you need urgent help, please visit the nearest hospital or emergency service immediately.
                    </p>
                    <p style="margin:0;font-size:15px;line-height:1.7;color:#35445a;">
                      Warm wishes for your quick recovery,<br>
                      <strong>The Medi Meet Team</strong>
                    </p>
                  </td>
                </tr>
                <tr>
                  <td style="padding:20px 30px;background:#f7fbfc;border-top:1px solid #dfe7ee;text-align:center;">
                    <p style="margin:0 0 6px;font-size:12px;line-height:1.6;color:#536175;font-weight:700;">Medi Meet - Online Doctor Consultation</p>
                    <p style="margin:0;font-size:12px;line-height:1.6;color:#7a8797;">
                      Sent from ${safeSupportEmail}. This email contains confidential medical information. Do not share it publicly.
                    </p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </body>
    </html>
  `;
};

module.exports = {
  buildPrescriptionEmailHtml,
  buildPrescriptionEmailSubject,
};
